<?php

function custom_portal_theme($existing, $type, $theme, $path) {
  return [
    'portal_options_page' => [
      'variables' => ['links' => []],
      'template' => 'portal-options-page',
    ],
     'custom_portal_distributor_form' => [
      'render element' => 'form',
      'template' => 'distributor-form',
    ],
    'custom_portal_hcp_form' => [
      'render element' => 'form',
      'template' => 'hcp-form',
    ],
  ];
}